// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using booking_hotel_backend.Data;

#nullable disable

namespace booking_hotel_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717154434_fix table shiffChange")]
    partial class fixtableshiffChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.Amenity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Icon")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("amenities");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.Attendance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<TimeOnly?>("CheckInTime")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly?>("CheckOutTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("WorkScheduleId")
                        .HasColumnType("bigint")
                        .HasColumnName("work_schedule_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkScheduleId")
                        .IsUnique();

                    b.ToTable("attendances");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.Booking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("booking_code");

                    b.Property<DateTime>("Checkin")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("checkin");

                    b.Property<DateTime>("Checkout")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("checkout");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int")
                        .HasColumnName("payment_status");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("room_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RoomId");

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.BookingSurcharge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("approved_at");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int")
                        .HasColumnName("approved_by");

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("HotelSurchargeId")
                        .HasColumnType("bigint")
                        .HasColumnName("hotel_surcharge_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTime?>("RequestedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("requested_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("BookingId");

                    b.HasIndex("HotelSurchargeId");

                    b.ToTable("booking_surcharges");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.Hotel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("address");

                    b.Property<long>("BrandId")
                        .HasColumnType("bigint")
                        .HasColumnName("brand_id");

                    b.Property<TimeOnly>("CheckinTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("checkin_time");

                    b.Property<TimeOnly>("CheckoutTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("checkout_time");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("image");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("slug");

                    b.Property<byte>("Star")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("star");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("hotels");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.HotelAmenity", b =>
                {
                    b.Property<long>("HotelId")
                        .HasColumnType("bigint")
                        .HasColumnName("hotel_id");

                    b.Property<long>("AmenityId")
                        .HasColumnType("bigint")
                        .HasColumnName("amenity_id");

                    b.HasKey("HotelId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("hotel_amenities");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.HotelBrand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Banner")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("banner");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Logo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("slug");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("website");

                    b.HasKey("Id");

                    b.ToTable("hotel_brands");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.HotelStaff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("employee_code");

                    b.Property<long>("HotelId")
                        .HasColumnType("bigint")
                        .HasColumnName("hotel_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("PositionId")
                        .HasColumnType("bigint")
                        .HasColumnName("position_id");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("PositionId");

                    b.HasIndex("UserId");

                    b.ToTable("hotel_staffs");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.HotelSurcharge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("AmountType")
                        .HasColumnType("int")
                        .HasColumnName("amount_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("end_time");

                    b.Property<long>("HotelId")
                        .HasColumnType("bigint")
                        .HasColumnName("hotel_id");

                    b.Property<bool>("IsRequest")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_request");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<long>("SurchargeTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("surcharge_type_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("SurchargeTypeId");

                    b.ToTable("hotel_surcharges");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.LeaveRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date")
                        .HasColumnName("from_date");

                    b.Property<long?>("HotelStaffId")
                        .HasColumnType("bigint");

                    b.Property<long>("StaffRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("staff_request_id");

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("date")
                        .HasColumnName("to_date");

                    b.HasKey("Id");

                    b.HasIndex("HotelStaffId");

                    b.HasIndex("StaffRequestId")
                        .IsUnique();

                    b.ToTable("leave_requests");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.OvertimeRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<TimeOnly>("FromTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("from_time");

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("hours");

                    b.Property<long>("StaffRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("staff_request_id");

                    b.Property<TimeOnly>("ToTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("to_time");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date")
                        .HasColumnName("work_date");

                    b.HasKey("Id");

                    b.HasIndex("StaffRequestId")
                        .IsUnique();

                    b.ToTable("overtime_requests");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.Position", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("positions");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.Room", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Floor")
                        .HasColumnType("int")
                        .HasColumnName("floor");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("image");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("room_number");

                    b.Property<long>("RoomTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("room_type_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("rooms");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.RoomType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BedType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("bed_type");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("HotelId")
                        .HasColumnType("bigint")
                        .HasColumnName("hotel_id");

                    b.Property<int>("MaxGuest")
                        .HasColumnType("int")
                        .HasColumnName("max_guest");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("RoomSize")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("room_size");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("room_types");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.Salary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Allowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Deduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("HotelStaffId")
                        .HasColumnType("bigint")
                        .HasColumnName("hotel_staff_id");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotalSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelStaffId");

                    b.ToTable("salaries");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.Shift", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BreakMinutes")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<long>("HotelId")
                        .HasColumnType("bigint")
                        .HasColumnName("hotel_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(6)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("shifts");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.ShiftChangeRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("NewShiftId")
                        .HasColumnType("bigint")
                        .HasColumnName("new_shift_id");

                    b.Property<DateOnly?>("NewWorkDate")
                        .HasColumnType("date")
                        .HasColumnName("new_work_date");

                    b.Property<long>("StaffRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("staff_request_id");

                    b.Property<long?>("TargetWorkScheduleId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_work_schedule_id");

                    b.Property<long>("WorkScheduleId")
                        .HasColumnType("bigint")
                        .HasColumnName("work_schedule_id");

                    b.HasKey("Id");

                    b.HasIndex("NewShiftId");

                    b.HasIndex("StaffRequestId")
                        .IsUnique();

                    b.HasIndex("TargetWorkScheduleId");

                    b.HasIndex("WorkScheduleId");

                    b.ToTable("shift_change_requests");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.StaffRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("approved_at");

                    b.Property<long?>("ApprovedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("approved_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("HotelStaffId")
                        .HasColumnType("bigint")
                        .HasColumnName("hotel_staff_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("reason");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("reject_reason");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HotelStaffId");

                    b.ToTable("staff_requests");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.SurchargeType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("surcharge_types");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Verified")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.WorkSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("HotelStaffId")
                        .HasColumnType("bigint")
                        .HasColumnName("hotel_staff_id");

                    b.Property<bool>("IsDayOff")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("ShiftId")
                        .HasColumnType("bigint")
                        .HasColumnName("shift_id");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("HotelStaffId");

                    b.HasIndex("ShiftId");

                    b.ToTable("work_schedules");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.Attendance", b =>
                {
                    b.HasOne("booking_hotel_backend.Models.Entities.WorkSchedule", "WorkSchedule")
                        .WithOne("Attendance")
                        .HasForeignKey("booking_hotel_backend.Models.Entities.Attendance", "WorkScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkSchedule");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.Booking", b =>
                {
                    b.HasOne("booking_hotel_backend.Models.Entities.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("booking_hotel_backend.Models.Entities.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.BookingSurcharge", b =>
                {
                    b.HasOne("booking_hotel_backend.Models.Entities.User", "ApprovedUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy");

                    b.HasOne("booking_hotel_backend.Models.Entities.Booking", "Booking")
                        .WithMany("BookingSurcharges")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("booking_hotel_backend.Models.Entities.HotelSurcharge", "HotelSurcharge")
                        .WithMany("BookingSurcharges")
                        .HasForeignKey("HotelSurchargeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedUser");

                    b.Navigation("Booking");

                    b.Navigation("HotelSurcharge");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.Hotel", b =>
                {
                    b.HasOne("booking_hotel_backend.Models.Entities.HotelBrand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.HotelAmenity", b =>
                {
                    b.HasOne("booking_hotel_backend.Models.Entities.Amenity", "Amenity")
                        .WithMany("HotelAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("booking_hotel_backend.Models.Entities.Hotel", "Hotel")
                        .WithMany("HotelAmenities")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.HotelStaff", b =>
                {
                    b.HasOne("booking_hotel_backend.Models.Entities.Hotel", "Hotel")
                        .WithMany("HotelStaffs")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("booking_hotel_backend.Models.Entities.Position", "Position")
                        .WithMany("HotelStaffs")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("booking_hotel_backend.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("Position");

                    b.Navigation("User");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.HotelSurcharge", b =>
                {
                    b.HasOne("booking_hotel_backend.Models.Entities.Hotel", "Hotel")
                        .WithMany("HotelSurcharges")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("booking_hotel_backend.Models.Entities.SurchargeType", "SurchargeType")
                        .WithMany("Surcharges")
                        .HasForeignKey("SurchargeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("SurchargeType");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.LeaveRequest", b =>
                {
                    b.HasOne("booking_hotel_backend.Models.Entities.HotelStaff", null)
                        .WithMany("LeaveRequests")
                        .HasForeignKey("HotelStaffId");

                    b.HasOne("booking_hotel_backend.Models.Entities.StaffRequest", "StaffRequest")
                        .WithOne("LeaveRequest")
                        .HasForeignKey("booking_hotel_backend.Models.Entities.LeaveRequest", "StaffRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaffRequest");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.OvertimeRequest", b =>
                {
                    b.HasOne("booking_hotel_backend.Models.Entities.StaffRequest", "StaffRequest")
                        .WithOne("OvertimeRequest")
                        .HasForeignKey("booking_hotel_backend.Models.Entities.OvertimeRequest", "StaffRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaffRequest");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.Room", b =>
                {
                    b.HasOne("booking_hotel_backend.Models.Entities.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.RoomType", b =>
                {
                    b.HasOne("booking_hotel_backend.Models.Entities.Hotel", "Hotel")
                        .WithMany("RoomTypes")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.Salary", b =>
                {
                    b.HasOne("booking_hotel_backend.Models.Entities.HotelStaff", "HotelStaff")
                        .WithMany("Salaries")
                        .HasForeignKey("HotelStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HotelStaff");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.Shift", b =>
                {
                    b.HasOne("booking_hotel_backend.Models.Entities.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.ShiftChangeRequest", b =>
                {
                    b.HasOne("booking_hotel_backend.Models.Entities.Shift", "NewShift")
                        .WithMany()
                        .HasForeignKey("NewShiftId");

                    b.HasOne("booking_hotel_backend.Models.Entities.StaffRequest", "StaffRequest")
                        .WithOne("ShiftChangeRequest")
                        .HasForeignKey("booking_hotel_backend.Models.Entities.ShiftChangeRequest", "StaffRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("booking_hotel_backend.Models.Entities.WorkSchedule", "TargetWorkSchedule")
                        .WithMany()
                        .HasForeignKey("TargetWorkScheduleId");

                    b.HasOne("booking_hotel_backend.Models.Entities.WorkSchedule", "WorkSchedule")
                        .WithMany()
                        .HasForeignKey("WorkScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewShift");

                    b.Navigation("StaffRequest");

                    b.Navigation("TargetWorkSchedule");

                    b.Navigation("WorkSchedule");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.StaffRequest", b =>
                {
                    b.HasOne("booking_hotel_backend.Models.Entities.HotelStaff", "HotelStaff")
                        .WithMany()
                        .HasForeignKey("HotelStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HotelStaff");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.WorkSchedule", b =>
                {
                    b.HasOne("booking_hotel_backend.Models.Entities.HotelStaff", "HotelStaff")
                        .WithMany("WorkSchedules")
                        .HasForeignKey("HotelStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("booking_hotel_backend.Models.Entities.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HotelStaff");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.Amenity", b =>
                {
                    b.Navigation("HotelAmenities");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.Booking", b =>
                {
                    b.Navigation("BookingSurcharges");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.Hotel", b =>
                {
                    b.Navigation("HotelAmenities");

                    b.Navigation("HotelStaffs");

                    b.Navigation("HotelSurcharges");

                    b.Navigation("RoomTypes");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.HotelStaff", b =>
                {
                    b.Navigation("LeaveRequests");

                    b.Navigation("Salaries");

                    b.Navigation("WorkSchedules");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.HotelSurcharge", b =>
                {
                    b.Navigation("BookingSurcharges");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.Position", b =>
                {
                    b.Navigation("HotelStaffs");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.Room", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.StaffRequest", b =>
                {
                    b.Navigation("LeaveRequest");

                    b.Navigation("OvertimeRequest");

                    b.Navigation("ShiftChangeRequest");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.SurchargeType", b =>
                {
                    b.Navigation("Surcharges");
                });

            modelBuilder.Entity("booking_hotel_backend.Models.Entities.WorkSchedule", b =>
                {
                    b.Navigation("Attendance");
                });
#pragma warning restore 612, 618
        }
    }
}
